config/routes.rb
Rails.application.routes.draw do
  resources :testmigs
  get 'images/download'

  resources :images
  resources :regions
  resources :payoffs
  resources :images do
    member do
      get 'download'
    end
  end
    
  resources :projects 
  get 'projects/select'
  resources :hpusers
  root to: 'visitors#index'
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
end

app/models/hpuser.rb
class Hpuser < ActiveRecord::Base
end

app/controllers/hpusers_controller.rb
class HpusersController < ApplicationController
  before_action :set_hpuser, only: [:show, :edit, :update, :destroy]

  # GET /hpusers
  # GET /hpusers.json
  def index
    @hpusers = Hpuser.all
  end

  # GET /hpusers/1
  # GET /hpusers/1.json
  def show
  end

  # GET /hpusers/new
  def new
    @hpuser = Hpuser.new
  end

  # GET /hpusers/1/edit
  def edit
  end

  # POST /hpusers
  # POST /hpusers.json
  def create
    @hpuser = Hpuser.new(hpuser_params)

    respond_to do |format|
      if @hpuser.save
        format.html { redirect_to @hpuser, notice: 'Hpuser was successfully created.' }
        format.json { render :show, status: :created, location: @hpuser }
      else
        format.html { render :new }
        format.json { render json: @hpuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hpusers/1
  # PATCH/PUT /hpusers/1.json
  def update
    respond_to do |format|
      if @hpuser.update(hpuser_params)
        format.html { redirect_to @hpuser, notice: 'Hpuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @hpuser }
      else
        format.html { render :edit }
        format.json { render json: @hpuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hpusers/1
  # DELETE /hpusers/1.json
  def destroy
    @hpuser.destroy
    respond_to do |format|
      format.html { redirect_to hpusers_url, notice: 'Hpuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hpuser
      @hpuser = Hpuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hpuser_params
      params.require(:hpuser).permit(:username, :password, :email, :client_id, :client_secret)
    end
end

app/helpers/hpusers_helper.rb
module HpusersHelper
end

app/views/hpusers/_form.html.erb
<%= simple_form_for(@hpuser) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :password %>
    <%= f.input :email %>
    <%= f.input :client_id %>
    <%= f.input :client_secret %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hpusers/edit.html.erb
<h1>Editing Hpuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @hpuser %> |
<%= link_to 'Back', hpusers_path %>

app/views/hpusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hpusers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Client</th>
      <th>Client secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hpusers.each do |hpuser| %>
      <tr>
        <td><%= hpuser.username %></td>
        <td><%= hpuser.password %></td>
        <td><%= hpuser.email %></td>
        <td><%= hpuser.client_id %></td>
        <td><%= hpuser.client_secret %></td>
        <td><%= link_to 'Show', hpuser %></td>
        <td><%= link_to 'Edit', edit_hpuser_path(hpuser) %></td>
        <td><%= link_to 'Destroy', hpuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hpuser', new_hpuser_path %>

app/views/hpusers/new.html.erb
<h1>New Hpuser</h1>

<%= render 'form' %>

<%= link_to 'Back', hpusers_path %>

app/views/hpusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @hpuser.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @hpuser.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @hpuser.email %>
</p>

<p>
  <strong>Client:</strong>
  <%= @hpuser.client_id %>
</p>

<p>
  <strong>Client secret:</strong>
  <%= @hpuser.client_secret %>
</p>

<%= link_to 'Edit', edit_hpuser_path(@hpuser) %> |
<%= link_to 'Back', hpusers_path %>