config/routes.rb
Rails.application.routes.draw do
  resources :testmigs
  get 'images/download'

  resources :images
  resources :regions
  resources :payoffs
  resources :images do
    member do
      get 'download'
    end
  end
    
  resources :projects 
  get 'projects/select'
  resources :hpusers
  root to: 'visitors#index'
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
end

app/models/testmig.rb
class Testmig < ActiveRecord::Base
end

app/controllers/testmigs_controller.rb
class TestmigsController < ApplicationController
  before_action :set_testmig, only: [:show, :edit, :update, :destroy]

  # GET /testmigs
  # GET /testmigs.json
  def index
    @testmigs = Testmig.all
  end

  # GET /testmigs/1
  # GET /testmigs/1.json
  def show
  end

  # GET /testmigs/new
  def new
    @testmig = Testmig.new
  end

  # GET /testmigs/1/edit
  def edit
  end

  # POST /testmigs
  # POST /testmigs.json
  def create
    @testmig = Testmig.new(testmig_params)

    respond_to do |format|
      if @testmig.save
        format.html { redirect_to @testmig, notice: 'Testmig was successfully created.' }
        format.json { render :show, status: :created, location: @testmig }
      else
        format.html { render :new }
        format.json { render json: @testmig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testmigs/1
  # PATCH/PUT /testmigs/1.json
  def update
    respond_to do |format|
      if @testmig.update(testmig_params)
        format.html { redirect_to @testmig, notice: 'Testmig was successfully updated.' }
        format.json { render :show, status: :ok, location: @testmig }
      else
        format.html { render :edit }
        format.json { render json: @testmig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testmigs/1
  # DELETE /testmigs/1.json
  def destroy
    @testmig.destroy
    respond_to do |format|
      format.html { redirect_to testmigs_url, notice: 'Testmig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testmig
      @testmig = Testmig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testmig_params
      params.require(:testmig).permit(:name, :email)
    end
end

app/helpers/testmigs_helper.rb
module TestmigsHelper
end

app/views/testmigs/_form.html.erb
<%= simple_form_for(@testmig) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testmigs/edit.html.erb
<h1>Editing Testmig</h1>

<%= render 'form' %>

<%= link_to 'Show', @testmig %> |
<%= link_to 'Back', testmigs_path %>

app/views/testmigs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testmigs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testmigs.each do |testmig| %>
      <tr>
        <td><%= testmig.name %></td>
        <td><%= testmig.email %></td>
        <td><%= link_to 'Show', testmig %></td>
        <td><%= link_to 'Edit', edit_testmig_path(testmig) %></td>
        <td><%= link_to 'Destroy', testmig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testmig', new_testmig_path %>

app/views/testmigs/new.html.erb
<h1>New Testmig</h1>

<%= render 'form' %>

<%= link_to 'Back', testmigs_path %>

app/views/testmigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @testmig.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @testmig.email %>
</p>

<%= link_to 'Edit', edit_testmig_path(@testmig) %> |
<%= link_to 'Back', testmigs_path %>